### ISSUE TITLE
Mouse clicks getting "stuck"

### ISSUE THREAD

**Issue by jamesnvc** [keyboardio/Kaleidoscope-MouseKeys#10]
It seems that the default behaviour of the mouse click keys is to simulate a hold, rather than a click.  This leads to confusing behaviour, where if I press the key bound to, for example, mouse right click, the right click on my physical mouse doesn't work until I press the keyboard right click twice more (and similarly for left click).

I'm not sure if this is intended behaviour, or if it's the result of something strange in my setup.  My mouse keys are on a one-shot activated layer and I'm using the keyboard on Ubuntu 16.04.

**Comment by algernon** [comment]
The reason this happens is because mousekey press & release are reported when the physical key is pressed and released. If that takes more than a scan cycle (and it usually does), that will be seen the host as a button hold.

This was originally done this way - as far as I can remember - to allow one to hold a mousekey.

Mind you, this is indeed a bit of a surprising behaviour, so perhaps we should only "click" after a timeout, or on release? Those have some consequences too...

**Comment by jamesnvc** [comment]
I just spent like ten minutes trying to figure out why my computer was possessed and eventually figured out that the middle mouse button was being held down…I think this default behaviour is potentially very confusing.

Maybe the default behaviour should be to just send a click and like shift held down means the separate up-and-down events for dragging?

**Comment by algernon** [comment]
I *think* I understand what is happening! The good news is, that we can fix it with reasonable ease.

So here's the thing:

- Hold `Fn`.
- Press and hold a mouse button.
- Release `Fn`.
- Release the mouse button.
- Observe that the button is still held.

This is because due to `Fn` releasing sooner, we never release the mouse key. Unlike with normal keys, we do *not* clear the mouse report every cycle.

The solution is to make `Mouse` (and possibly `AbsoluteMouse`) work like the keyboard, and clear the report every cycle. Consequently, it should only send one report per cycle too.
