### ISSUE TITLE
Modifiers and mouse buttons cannot be assigned to a single button

### ISSUE THREAD

**Issue by LA-Toth** [keyboardio/Kaleidoscope-MouseKeys#21]
I would like to send Control-Alt-LeftClick by pressing a single button.
I tried to assign LCTRL(LALT(Key_mouseBtnL)), but it has no effect.

**Comment by algernon** [comment]
`LCTRL(LALT(Key_mouseBtnL))` doesn't work because the keycodes on the keymap are 16bit only, and the `LCTRL` and `LALT` macros only work on the lower 8 - that happen to cover the basic keys on a keyboard. `Key_mouseBtnL` uses more than 8 bits, so when the `LCTRL` and `LALT` modifiers are applied, it is no longer recognised as a mouse key.

To accomplish the same thing, you can use a macro:

```c++
return MACRODOWN(D(LeftControl), D(LeftAlt), T(mouseBtnL), U(LeftAlt), U(LeftControl));
```

This does not support holding the key, though. If you want to hold the key, and have it send the combination while held:

```c++
if (keyIsPressed(keyState)) {
  return MACRO(...);
}
```

Hope that helps!

**Comment by LA-Toth** [comment]
Thanks, with a minimal change it works. I need to hold the key:

```
const macro_t *macroAction(uint8_t macroIndex, uint8_t keyState) {
...
  case MACRO_CTRL_ALT_LCLICK:
      if (keyIsPressed(keyState)) {
        return MACRO(D(LeftControl), D(LeftAlt), D(mouseBtnL));
      }      
```

**Comment by LA-Toth** [comment]
Can you update the README with the usage of CTRL and other modifiers? Thanks

**Comment by algernon** [comment]
I have updated the [Kaleidoscope Wiki](https://github.com/keyboardio/Kaleidoscope/wiki/Keycode-meanings#in-keymap-chorded-keys), which seemed like the best place to have this documented.

(This is not specific to MouseKeys, so adding this info to the MouseKeys README would not be appropriate. We would need to add it to every other plugin README too. Better to document them at the source then.)

Glad to hear you got it working!
